services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: trading_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - trading_network

  # ZooKeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: trading_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD-SHELL", "nc -z zookeeper 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - trading_network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: trading_kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - trading_network

  # Trading Bot Application
  trading_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trading_app
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      # Redis
      - REDIS_URL=redis://redis:6379/0
      - REDIS_MAX_CONNECTIONS=10
      
      # Celery
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      
      # Kafka
      - KAFKA_SERVERS=kafka:29092
      - KAFKA_TOPIC_NOTIFICATIONS=trading_notifications
      
      # Telegram Bot
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_TELEGRAM_IDS=${ADMIN_TELEGRAM_IDS}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      
      # Bybit API
      - TRADER_API_KEY=${TRADER_API_KEY}
      - TRADER_API_SECRET=${TRADER_API_SECRET}
      - TRADER_ID=${TRADER_ID}
      
      # Encryption
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./logs:/app/logs
      - ./database.db:/app/database.db
    networks:
      - trading_network
    restart: unless-stopped

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A trading.celery_worker worker --loglevel=info --concurrency=4
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      # Redis
      - REDIS_URL=redis://redis:6379/0
      - REDIS_MAX_CONNECTIONS=10
      
      # Celery
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      
      # Kafka
      - KAFKA_SERVERS=kafka:29092
      - KAFKA_TOPIC_NOTIFICATIONS=trading_notifications
      
      # Bybit API
      - TRADER_API_KEY=${TRADER_API_KEY}
      - TRADER_API_SECRET=${TRADER_API_SECRET}
      - TRADER_ID=${TRADER_ID}
      
      # Encryption
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./logs:/app/logs
      - ./database.db:/app/database.db
    networks:
      - trading_network
    restart: unless-stopped

networks:
  trading_network:
    driver: bridge

volumes:
  redis_data:
  zookeeper_data:
  zookeeper_logs:
  kafka_data: